version: '3'
services: 
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres-db
    volumes:
      - ./pgdata:/postgresql/data
  nestjs:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: transcendence:latest
    environment: 
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=false
      - POSTGRES_PORT=${DB_PORT}
      - APP_PORT=${APP_PORT}
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
    ports: 
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    container_name: nest-transcendence
    depends_on: 
      - db
    volumes: 
      - .:/app
      - /app/node_modules
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports: 
      - "8080:80"
    volumes: 
      - ./pgadmin-data:/pgadmin
    depends_on: 
      - db
volumes:
  pgdata:
  pgadmin-data: