version: '3'
services: 
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    container_name: postgres-db
    volumes:
      - ./pgdata:/postgresql/data
  backend:
    build: 
      context: ./Backend
      dockerfile: ./Dockerfile
    image: backend:latest
    restart: always
    environment: 
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_SYNC=false
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_HOST=${HOSTNAME}
      - APP_PORT=${APP_PORT}
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
      - FORTYTWO_CLIENT_ID=${FORTYTWO_CLIENT_ID}
      - FORTYTWO_CLIENT_SECRET=${FORTYTWO_CLIENT_SECRET}
    ports: 
      - "8000:8000"
    container_name: backend-transcendence
    depends_on: 
      - db
    volumes: 
      - './Backend:/app'
      - /app/node_modules/
  frontend:
    build:
      context: ./Frontend
      dockerfile: ./Dockerfile
    image: frontend:latest
    restart: always
    environment:
      - REACT_APP_HOST=${APP_HOST}
    ports:
      - "3000:3000"
    container_name: frontend-transcendence
    volumes:
      - './Frontend:/app'
      - /app/node_modules/
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports: 
      - "8080:80"
    volumes: 
      - ./pgadmin-data:/pgadmin
    depends_on: 
      - db
volumes:
  pgdata:
  pgadmin-data:
